### ISSUE TITLE
`MediaPipeException: unknown: Could not build model from the provided pre-loaded flatbuffer: The model allocation is null/empty`

### ISSUE THREAD

**Issue by shubham0204** [shubham0204/AirDrawing_with_Mediapipe_Android#1]
After downloading `hand_landmarker.task` with `download_tasks.gradle`, MediaPipe is unable to build the graph for the hand landmarker model and throws the following exception:

```
com.google.mediapipe.framework.MediaPipeException: unknown: Could not build model from the provided pre-loaded flatbuffer: The model allocation is null/empty
at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:336)
at com.google.mediapipe.tasks.core.TaskRunner.create(TaskRunner.java:71)
at com.google.mediapipe.tasks.vision.handlandmarker.HandLandmarker.createFromOptions(HandLandmarker.java:183)
at com.shubham0204.ml.mediapipehandsdemo.FrameAnalyzer.setupHandLandmarker(FrameAnalyzer.kt:76)
at com.shubham0204.ml.mediapipehandsdemo.MainActivity.onCreate$lambda-0(MainActivity.kt:94)
```

**Comment by shubham0204** [comment]
This issue was resolved by https://github.com/google/mediapipe/issues/4178#issuecomment-1482148431
